on:
  push:
    branches:
      - main

jobs:
  job_id_1:
    runs-on: ubuntu-latest
    name: My first workflow job
    permissions: read-all|write-all

    steps:
      - name: Checkout action
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Run Python Script
        run: python main.py

      - name: Run 2 Python Scripts
        run: |
          python main.py
          python main.py
