name: My First GitHub Actions Workflow

on:
  push:
    # branches: [main, master]
    branches:
      - main
      - master

jobs:
  job_id_1:
    runs-on: ubuntu-latest
    name: My First Workflow Job
    # permissions: read-all|write-all

    steps:
      - name: Checkout Pre-Built Action
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: PyTest
        run: pytest

      - name: Linux Commands
        run: |
          echo "Hello GitHub Actions"
          python3 --version
